return { 
 ["flashnuke"] = {
    groundflash = {
      circlealpha        = 0.2,
      circlegrowth       = 10,
      flashalpha         = 1.8,
      flashsize          = 120,
      ttl                = 15,
      color = {
        [1]  = 1,
        [2]  = 0.69999998807907,
        [3]  = 0.69999998807907,
      },
    },
    smokecloud_fast = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1, 
      ground             = true,
      underwater         = 0,
      water              = true,
      properties = {
        airdrag            = 0.825,
        colormap           = [[0.5 0.3 0.1 0.3		0.3 0.2 0.1 0.4		0.1 0.1 0.1 0.3		0.1 0.1 0.1 0.3	 0 0 0 0.00]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 360,
        emitvector         = [[0,1,0]],
        gravity            = [[0 , 0.0012, 0]],
        numparticles       = 30,
        particlelife       = 20,
        particlelifespread = 130,
        particlesize       = 30,
        particlesizespread = 25,
        particlespeed      = [[5 i-0.75]],
        particlespeedspread = 5,
        pos                = [[-13 r13,-13 r13,-13 r13]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[smoke]],
        useairlos          = true,
      },
    },
  },
}
